import Footer from "@/components/common/Footer";
import Header from "@/components/common/Header";
import { Lato, Quicksand } from "next/font/google";
import "./globals.css";

const quicksand = Quicksand({
  variable: "--font-quicksand-sans",
  subsets: ["latin"],
}); 
const lato = Lato({
  variable: "--font-lato-sans",
  subsets: ["latin"],
  weight:"100",
}); 

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${quicksand.variable} ${lato.variable} antialiased`}
      >
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
