import { Geist, Geist_Mono, Lato, Poppins, Quicksand } from "next/font/google";
import "./globals.css";
import Header from "@/components/common/Header";
import Footer from "@/components/common/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const poppins = Poppins({
  variable: "--font-poppins-sans",
  subsets: ["latin"],
  weight:"700",
});
const lato = Lato({
  variable: "--font-lato-sans",
  subsets: ["latin"],
  weight:"700",
});
const quicksand = Quicksand({
  variable: "--font-quicksand-sans",
  subsets: ["latin"],
  weight:"700",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${lato.variable} ${poppins.variable}  ${quicksand.variable} antialiased`}
      >
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
